FROM petkr/gdal-python-alpine
#FROM ubuntu:18.10

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

#RUN apk add --update --no-cache python3  \
#    && ln -sf python3 /usr/bin/python  \
#    && apk --no-cache add musl-dev linux-headers g++
#RUN python3 -m ensurepip
#RUN pip3 install --no-cache --upgrade pip setuptools

WORKDIR /usr/src

#RUN #apk update && \
#    apt-get -yq install \
#    libhdf5-dev \
#    libnetcdf-dev \
#    libgdal-dev \
#    libyaml-dev \
#    python \
#    python-dev \
#    python-pip \
#    python-virtualenv \
#    cython \
#    python3 \
#    python3-dev \
#    python3-pip \
#    cython3 && \
#    rm -rf /var/lib/apt/lists/* \

RUN apk add --update py-pip

RUN pip install --upgrade pip \
    && apk add --update --no-cache --virtual .tmp-build-deps \
#    && apk add libhdf5-dev libnetcdf-dev libgdal-dev libyaml-dev cython3 python3-pip python3-dev cython python3 \
#    && apk add  python-virtualenv \
    && apk add --no-cache --update python3 python3-dev gfortran gcc libc-dev linux-headers musl-dev zlib zlib-dev libffi-dev
RUN apk add --no-cache --update \
    python3 python3-dev gcc \
    gfortran musl-dev

RUN pip install -U pip && python3 -m pip install -U pip

RUN pip install numpy && pip3 install numpy
#
RUN pip install gdal==2.3.1 h5py netCDF4 psycopg2 PyYAML pillow
#
RUN pip3 install gdal==2.3.1 h5py netCDF4 psycopg2 PyYAML pillow

#COPY requirements.txt .
#
#RUN pip install -r requirements.txt

COPY . .

CMD ["python", "tiff2nc"]
